on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  release:
    name: publish release on github
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        # NOTE(ww): GitHub actions doesn't allow workflows to trigger other workflows
        # by default. The workaround is to use a PAT instead of the default GITHUB_TOKEN.
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'rc') }}
